"""
Theme definitions for Sobriety Counter GUI.
Each theme is a dict of color tokens used throughout the UI.
"""

THEMES = {
    "dark": {
        "name": "Dark",
        "bg": "#0f0f23",
        "card_bg": "#1a1a2e",
        "card_border": "#2a2a40",
        "quote_bg": "#16213e",
        "fg": "#ffffff",
        "fg_dim": "#a0a0a0",
        "accent": "#5B86E5",
        "accent_hover": "#4a75d4",
        "accent2": "#36D1DC",
        "warning": "#E67E22",
        "warning_hover": "#d56d11",
        "success": "#2ecc71",
        "danger": "#e74c3c",
        "input_bg": "#2a2a40",
        "divider": "#2a2a40",
        "sidebar_bg": "#0a0a1a",
        "sidebar_item": "#1a1a2e",
        "sidebar_item_active": "#252545",
        "button_fg": "#000000",
        "tray_fg": "#ffffff",
    },
    "light": {
        "name": "Light",
        "bg": "#f5f5f5",
        "card_bg": "#ffffff",
        "card_border": "#e0e0e0",
        "quote_bg": "#e8f4f8",
        "fg": "#1a1a2e",
        "fg_dim": "#666666",
        "accent": "#3a6fd8",
        "accent_hover": "#2d5bb8",
        "accent2": "#1a9aaa",
        "warning": "#e67e22",
        "warning_hover": "#d56d11",
        "success": "#27ae60",
        "danger": "#c0392b",
        "input_bg": "#ffffff",
        "divider": "#e0e0e0",
        "sidebar_bg": "#e8e8e8",
        "sidebar_item": "#f0f0f0",
        "sidebar_item_active": "#d8d8f0",
        "button_fg": "#ffffff",
        "tray_fg": "#1a1a2e",
    },
    "ocean": {
        "name": "Ocean",
        "bg": "#0b1628",
        "card_bg": "#112240",
        "card_border": "#1d3461",
        "quote_bg": "#0d1f3c",
        "fg": "#ccd6f6",
        "fg_dim": "#8892b0",
        "accent": "#64ffda",
        "accent_hover": "#45e6c2",
        "accent2": "#57cbff",
        "warning": "#f0a500",
        "warning_hover": "#d99400",
        "success": "#64ffda",
        "danger": "#ff6b6b",
        "input_bg": "#1d3461",
        "divider": "#1d3461",
        "sidebar_bg": "#071120",
        "sidebar_item": "#112240",
        "sidebar_item_active": "#1d3461",
        "button_fg": "#0b1628",
        "tray_fg": "#ccd6f6",
    },
    "forest": {
        "name": "Forest",
        "bg": "#1a2e1a",
        "card_bg": "#2d4a2d",
        "card_border": "#3d6b3d",
        "quote_bg": "#243d24",
        "fg": "#e0f0e0",
        "fg_dim": "#a0c0a0",
        "accent": "#7ddf64",
        "accent_hover": "#6bcf52",
        "accent2": "#a8e6cf",
        "warning": "#f4a460",
        "warning_hover": "#e09050",
        "success": "#7ddf64",
        "danger": "#e07060",
        "input_bg": "#3d6b3d",
        "divider": "#3d6b3d",
        "sidebar_bg": "#142414",
        "sidebar_item": "#2d4a2d",
        "sidebar_item_active": "#3d6b3d",
        "button_fg": "#1a2e1a",
        "tray_fg": "#e0f0e0",
    },
}

DEFAULT_THEME = "dark"

TRACKER_CATEGORIES = [
    "Alcohol",
    "Smoking",
    "Substances",
    "Gambling",
    "Sugar",
    "Social Media",
    "Custom",
]

MOOD_EMOJIS = {
    1: "😞",
    2: "😐",
    3: "🙂",
    4: "😊",
    5: "😄",
}
